apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-eks
  region: us-east-2
  version: "1.29"

iam:
  withOIDC: true

vpc:
  nat:
    gateway: Disable

  clusterEndpoints:
    publicAccess: true
    privateAccess: false

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit"]

