apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JKBrindha/spring-boot-gitops.git
    targetRevision: main
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true