apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.21   # example, can be "latest"
    helm:
      values: |
        image:
          repository: ghcr.io/bitnami/postgresql
 
        auth:
          database: testdb
          username: postgres
          password: postgres

        primary:
          persistence:
            enabled: true
            size: 5Gi

        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 1Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: spring-boot-postgres-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
