apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    force-helm-render: "1"

spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.21   # example, can be "latest"
    helm:
      values: |
       global:
          imageRegistry: docker.io
        primary:
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: 16.3.0

          persistence:
            enabled: true
            size: 5Gi

        volumePermissions:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/os-shell
            tag: 12-debian-12-r0

        auth:
          database: testdb
          username: postgres
          password: postgres

        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 1Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: spring-boot-postgres-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
