apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/ignore-resource-health: |
      networking.k8s.io/Ingress
spec:
  project: default
  source:
    repoURL: https://github.com/JKBrindha/spring-boot-gitops.git
    targetRevision: main
    path: helm/spring-boot
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-boot-postgres-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
